### ISSUE TITLE
Vista de cuentos disponibles para cursos

### ISSUE THREAD

**Issue by ThisIsLexx** [ThisIsLexx/EUV#23]
# Antecedentes
En primera instancia, los cuentos no se muestran al usuario. Es necesario que se agregue una nueva vista que le permita al usuario ver los cuentos existentes para poder evaluar si desea unirse o no. De este modo, podemos agregar un enlace a la landing page para poder redirigir a este apartado.
# Requerimientos

- [x] Crear una nueva vista que tenga un listado de cuentos existentes para que los nuevos usuarios puedan visualizarlos
- [x] Esta vista es meramente informativa, no se deberan de poder realizar acciones (a considerar).
- [x] Cada cuento tendrá solo su dificultad (utilizar un banner con color para que sea más visual) y titulo

**Comment by osvaiglez** [comment]
@ThisIsLexx 
que tranza, duda rápida, el archivo al que pertenece esta vista es este:
resources/js/Pages/Cuentos/CuentoListado.vue
¿verdad?
