### ISSUE TITLE
Creación de seeder para textos en inglés

### ISSUE THREAD

**Issue by ThisIsLexx** [ThisIsLexx/EUV#5]
# Antecedentes
Actualmente se tiene el modelo Cuento dentro del sistema, el cual permite a los usuarios registrar cuentos dentro del sistema para que posteriormente puedan ser jugados por otros usuarios. Dentro del archivo **CuentoSeeder.php** se cuenta con una estructura básica de como se realiza el registro de textos en el sistema.

# Requerimientos
Es necesario tener una gran cantidad de textos de cuentos infantiles registrados dentro del sistema para que se tenga un catalogo para jugar. Esto para poder realizar una estadística con más registros al momento de aplicar un algoritmo para el módulo 3. 
- [x] Seguir la misma estructura de los registros existentes en CuentoSeeder.php para registrar más textos en inglés.
- [x] Realizar el registro de al menos 20 textos que tengan diferentes dificultades.
- [x] En `create_cuentos_table.php`  modificar la linea de `$table->text('contenido')` para agregar un valor máximo.

# Material de apoyo
Para trabajar las migraciones:
https://laravel.com/docs/11.x/migrations

**Comment by osvaiglez** [comment]
Yo me puedo rifar este durante la semana. ¿Qué te gustaría aclarar sobre este issue?

**Comment by ThisIsLexx** [comment]
Aclaraciones: El valor máximo en una cadena de texto aceptada por la base de datos es de 255. Los textos a utilizar pueden ser temáticas libres que elijas pero no pueden exceder el limite de caracteres. Según la dificultad o complejidad del texto, proporcionarla en el campo de dificultad del mismo archivo
